services:
  posteria:
    image: bozodev/posteria:latest
    container_name: posteria
    ports:
      - "8818:80"
    environment:
      - SITE_TITLE=Posteria

      - AUTH_USERNAME={ASK} # Change this!
      - AUTH_PASSWORD={ASK} # Change this!
      - SESSION_DURATION=3600 # In seconds
      - AUTH_BYPASS=false # DO NOT USE if you expose Posteria outside your local network

      - IMAGES_PER_PAGE=24
      - MAX_FILE_SIZE=5242880 # In bytes

      - PLEX_SERVER_URL={ASK}
      - PLEX_TOKEN={ASK}
      - PLEX_REMOVE_OVERLAY_LABEL=false # Set to true for Kometa compatibility

      - IGNORE_ARTICLES_IN_SORT=true # Set to false to sort with articles (A, An, The) included
      - SORT_BY_DATE_ADDED=false # Set to true to sort by Recently Added date in Plex instead of Alphabetically

      - AUTO_IMPORT_ENABLED=false # Enable/disable auto-import
      - AUTO_IMPORT_SCHEDULE=1h # Schedule 24h, 12h, 6h, 3h, 1h
      - AUTO_IMPORT_MOVIES=false # Import Movie posters
      - AUTO_IMPORT_SHOWS=false # Import TV Show posters
      - AUTO_IMPORT_SEASONS=false # Import TV season posters
      - AUTO_IMPORT_COLLECTIONS=false # Import Collection posters
    volumes:
      - ${APP_DATA_DIR}/posters:/var/www/html/posters
      - ${APP_DATA_DIR}/data:/var/www/html/data # Logs are found here
    restart: unless-stopped