services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    ports:
      - 9090:9090
    volumes:
      - ${APP_DATA_DIR}/data:/etc/linkding/data"
    restart: unless-stopped